### ISSUE TITLE
Make post archiving opt-in only

### ISSUE THREAD

**Issue by JoshAtticus** [mdwalters/Meower-Post-Archive#1]
![image](https://user-images.githubusercontent.com/72828296/204071023-845d3877-21ec-472d-ac83-be2a92708425.png)
![image](https://user-images.githubusercontent.com/72828296/204071035-ea49a541-e6da-444b-ae7f-dc73f086cef2.png)
![image](https://user-images.githubusercontent.com/72828296/204071050-e8c6818e-b370-42e0-bfc7-261f2327abf3.png)

**Comment by mdwalters** [comment]
uh

**Comment by theycallhermax** [comment]
closing, as the archive is now discontinued
